
# Site settings
title: Agilent Technologies -- iLab Design Guidelines
email:
description: > # this means to ignore newlines until "baseurl:"
  Guidelines for the iLab WebApp
url: "http://polycrystalline.github.io/" # the base hostname & protocol for your site
baseurl: /ilab-design-guidelines # the subpath of your site, e.g. /blog
twitter_username:
github_username:

# Build settings
markdown: kramdown

